name: Lint OpenAPI definition

# Run workflow on push to any branch
on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint Openapi spec
        run: redocly lint openapi.yaml
